TARGET        = main
SOURCES       = main.c motor.c
MCU           = atmega644p
F_CPU         = 1000000UL
PROGRAMMER    = avrispmkII
PORT          = usb
BAUD          = 9600
EXTRA_LDFLAGS = -lm

include ../../../labs/avr.mk
